venv/bin/python main.py \
    --mode train \
    --data_dir traindata/dataset \
    --batch_size 64 \
    --epochs 50 \
    --learning_rate 3e-5 \
    --weight_decay 0.01 \
    --checkpoint_dir traindata/checkpoints \
    --log_dir traindata/logs \
    --model_dir traindata/models \
    --output_dir traindata/outputs \
    --num_workers 16
